### ISSUE TITLE
failed to find src.model while running locally

### ISSUE THREAD

**Issue by AnnaSafaryan** [tchewik/corefhd#2]
I'm trying to run base model locally, but face the problem with module src.model which is now src.models. I've fixed it in [processor_corefhd](https://github.com/tchewik/corefhd/blob/193e7e933f424864a8bcf0898cd3e12cb17ee7e4/processor_corefhd.py#L3C10-L3C15), but there still incorrect names somewhere in the code (I cannot find).

```
"C:<my_path>\corefhd-local\venv\Scripts\python.exe" "C:<my_path>\corefhd-local\main.py" 
error loading _jsonnet (this is expected on Windows), treating C:\Users\annas\AppData\Local\Temp\tmpe8mum3fp\config.json as plain json
Traceback (most recent call last):
  File "C:<my_path>\corefhd-local\venv\lib\site-packages\allennlp\common\registrable.py", line 186, in resolve_class_name
    module = importlib.import_module(submodule)
  File "C:\Program Files\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'src.model'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:<my_path>\corefhd-local\main.py", line 17, in <module>
    corefhd_processor = (ProcessorCorefHD(cuda_device=-1, use_discourse=False),
  File "C:<my_path>\corefhd-local\processor_corefhd.py", line 10, in __init__
    self.model = LightCorefPredictor.from_path(os.path.join(model_dir, model_name),
  File "C:<my_path>\corefhd-local\venv\lib\site-packages\allennlp\predictors\predictor.py", line 366, in from_path
    load_archive(archive_path, cuda_device=cuda_device, overrides=overrides),
  File "C:<my_path>\corefhd-local\venv\lib\site-packages\allennlp\models\archival.py", line 232, in load_archive
    dataset_reader, validation_dataset_reader = _load_dataset_readers(
  File "C:<my_path>\corefhd-local\venv\lib\site-packages\allennlp\models\archival.py", line 268, in _load_dataset_readers
    dataset_reader = DatasetReader.from_params(
  File "C:<my_path>\corefhd-local\venv\lib\site-packages\allennlp\common\from_params.py", line 590, in from_params
    subclass, constructor_name = as_registrable.resolve_class_name(choice)
  File "C:<my_path>\corefhd-local\venv\lib\site-packages\allennlp\common\registrable.py", line 188, in resolve_class_name
    raise ConfigurationError(
allennlp.common.checks.ConfigurationError: tried to interpret src.model.light_conll.LightConllCorefReader as a path to a class but unable to import module src.model.light_conll
```

**Comment by tchewik** [comment]
Well, then rename the directory, I guess :) It is indeed src.model in the docker image.
I also commented in the first thread. If you use docker for windows, localhost ip (127.0.0.1) should work fine.
